services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    container_name: devlab-elasticsearch
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - devlab-net

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.17.10'
    container_name: devlab-kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - devlab-net

  redis:
    image: 'redis:latest'
    container_name: devlab-redis
    ports:
      - '6379:6379'
    networks:
      - devlab-net

  redis-insight:
    image: 'redis/redisinsight:latest'
    container_name: devlab-redis-insight
    ports:
      - '5540:5540'
    depends_on:
      - redis
    networks:
      - devlab-net

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    container_name: devlab-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - devlab-net

  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    container_name: devlab-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - devlab-net

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: devlab-kafka-ui
    ports:
      - '8090:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=devlab-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - devlab-net

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: devlab-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - devlab-net

  grafana:
    image: 'grafana/grafana:latest'
    container_name: devlab-grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    networks:
      - devlab-net

networks:
  devlab-net:
    driver: bridge
